import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Figtree, Noto_Sans, Playfair_Display, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavBar from "@/components/ui/navbar";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const playfairDisplayHeading = Playfair_Display({subsets:['latin'],variable:'--font-heading'});

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, playfairDisplayHeading.variable, jetbrainsMono.variable, "font-sans", geist.variable)}
    >
      <body className="min-h-screen flex flex-col">
        <NavBar/>
        <div className="px-5 flex-1 flex flex-col">
          {children}
        </div>
      </body>
    </html>
  );
}
